apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: kafka
    component: broker
    version: 3.4.0
  name: learnflow-kafka
  namespace: learnflow
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  serviceName: learnflow-kafka-headless
  template:
    metadata:
      labels:
        app: kafka
        component: broker
    spec:
      containers:
      - env:
        - name: KAFKA_BROKER_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper:2181
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: '3'
        - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
          value: '3'
        - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
          value: '2'
        - name: KAFKA_LOG_RETENTION_HOURS
          value: '168'
        - name: KAFKA_LOG_SEGMENT_BYTES
          value: '1073741824'
        - name: KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS
          value: '300000'
        - name: KAFKA_NUM_NETWORK_THREADS
          value: '3'
        - name: KAFKA_NUM_IO_THREADS
          value: '8'
        - name: KAFKA_SOCKET_SEND_BUFFER_BYTES
          value: '102400'
        - name: KAFKA_SOCKET_RECEIVE_BUFFER_BYTES
          value: '102400'
        - name: KAFKA_SOCKET_REQUEST_MAX_BYTES
          value: '104857600'
        image: confluentinc/cp-kafka:7.4.0
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 10
          tcpSocket:
            port: 9092
        name: kafka
        ports:
        - containerPort: 9092
          name: kafka
        - containerPort: 9999
          name: jmx
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - kafka-broker-api-versions --bootstrap-server localhost:9092
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi
        volumeMounts:
        - mountPath: /var/lib/kafka/data
          name: kafka-data
      volumes: []
  volumeClaimTemplates:
  - metadata:
      name: kafka-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
