apiVersion: v1
kind: Namespace
metadata:
  name: learnflow
  labels:
    name: learnflow
    environment: development
    managed-by: learnflow-m1
---
apiVersion: v1
kind: Namespace
metadata:
  name: dapr-system
  labels:
    name: dapr-system
    environment: development