apiVersion: v1
kind: Service
metadata:
  name: dapr-api
  namespace: dapr-system
spec:
  ports:
  - name: http
    port: 3500
    targetPort: 3500
  - name: grpc
    port: 50001
    targetPort: 50001
  selector:
    app: dapr-operator
